owner: aospapp
repo: upptime

sites:
  - name: Main Site
    url: https://aosp.app
  - name: China Site
    url: http://aosp.ylarod.cn
  - name: Backup Site
    url: https://tunnel.aosp.app

assignees:
  - Ylarod

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: status.aosp.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Aosp App Status
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://aosp.app
    - title: China Site
      href: http://aosp.ylarod.cn
    - title: Backup Site
      href: https://tunnel.aosp.app
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
