owner: aospapp
repo: upptime

sites:
  - name: Main Site
    url: https://aosp.app
  - name: android-14.0.0_r1
    url: https://aosp.app/android-14.0.0_r1
  - name: android-13.0.0_r1
    url: https://aosp.app/android-13.0.0_r1
  - name: android-12.1.0_r1
    url: https://aosp.app/android-12.1.0_r1
  - name: android-12.0.0_r1
    url: https://aosp.app/android-12.0.0_r1
  - name: android-11.0.0_r1
    url: https://aosp.app/android-11.0.0_r1
  - name: android-10.0.0_r1
    url: https://aosp.app/android-10.0.0_r1
  - name: android-9.0.0_r1
    url: https://aosp.app/android-9.0.0_r1
  - name: android-8.1.0_r1
    url: https://aosp.app/android-8.1.0_r1
  - name: android-8.0.0_r1
    url: https://aosp.app/android-8.0.0_r1
  - name: android-7.1.0_r1
    url: https://aosp.app/android-7.1.0_r1
  - name: android-7.0.0_r1
    url: https://aosp.app/android-7.0.0_r1
  - name: android-6.0.0_r1
    url: https://aosp.app/android-6.0.0_r1
  - name: android-5.1.0_r1
    url: https://aosp.app/android-5.1.0_r1
  - name: android-5.0.0_r1
    url: https://aosp.app/android-5.0.0_r1

assignees:
  - Ylarod

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: status.aosp.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Aosp App Status
  navbar:
    - title: Status
      href: /
    - title: Aosp App
      href: https://aosp.app
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
